apiVersion: v1
data:
  config.alloy: |
    otelcol.receiver.otlp "default" {
      grpc {}
      http {}

      output {
        traces  = [otelcol.processor.k8sattributes.default.input,otelcol.connector.servicegraph.default.input]
        metrics = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.k8sattributes "default" {
      extract {
        metadata = [
          "k8s.pod.uid",
          "k8s.pod.start_time",
        ]
      }
      output {
        traces  = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.connector.servicegraph "default" {
      dimensions = ["http.method"]
      output {
        metrics = [otelcol.exporter.prometheus.default.input]
      }
    }

    otelcol.processor.batch "default" {
      output {
        traces  = [otelcol.exporter.otlp.tempo.input]
        metrics = [otelcol.exporter.prometheus.default.input]
      }
    }

    otelcol.exporter.prometheus "default" {
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir-nginx.mimir.svc.cluster.local/api/v1/push"
        headers = {
          "X-Scope-OrgID" = "otelMetrics",
        }
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "http://tempo-distributor.tempo.svc.cluster.local:4317"
        tls {
            insecure             = true
            insecure_skip_verify = true
        }
      }
    }
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: alloy-traces
